FROM ubuntu:18.04
LABEL AUTHOR="SRIRAM"
LABEL ORG="QT"
RUN apt-get update && apt-get install openjdk-8-jdk -y
ADD https://spcjar1.s3.ap-south-1.amazonaws.com/spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar /spring-petclinic.jar
EXPOSE 8080
CMD ["java", "-jar", "/spring-petclinic.jar"]
 
